// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8IFjCzLyYn4bRshIkYmyIIvr2kwsll3s',
    appId: '1:637851002827:web:d45cee195975c4ad20384e',
    messagingSenderId: '637851002827',
    projectId: 'booble-translator',
    authDomain: 'booble-translator.firebaseapp.com',
    storageBucket: 'booble-translator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGipKUukqmwg2wS27JaSdB8W5Z1iGsnMs',
    appId: '1:637851002827:android:924d187afc3a29fe20384e',
    messagingSenderId: '637851002827',
    projectId: 'booble-translator',
    storageBucket: 'booble-translator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4UMeHo8Z_SUnYJH-NTosbjLLIXGoMHEQ',
    appId: '1:637851002827:ios:cd5a84af800d803120384e',
    messagingSenderId: '637851002827',
    projectId: 'booble-translator',
    storageBucket: 'booble-translator.appspot.com',
    iosBundleId: 'com.example.testBoobleTranslator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4UMeHo8Z_SUnYJH-NTosbjLLIXGoMHEQ',
    appId: '1:637851002827:ios:340b3091a680b64120384e',
    messagingSenderId: '637851002827',
    projectId: 'booble-translator',
    storageBucket: 'booble-translator.appspot.com',
    iosBundleId: 'com.example.testBoobleTranslator.RunnerTests',
  );
}
